################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/Atadisk.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/Atadiskfree.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_bytes.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_bytes_seek.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_bytes_write.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_chdir.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_fileinit.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_flush.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_labels.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_labels_label.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_labels_vol.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_names.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_readword.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_sector.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_timeout.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_usb.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atacreate.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atacreate_findcluster.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atacreatedir.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atadir.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atadir_.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atadir__getdir.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atadirentry.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ataformat.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atalong.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atalong_create.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atalong_create_rename.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atalong_createentry.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atalong_setname.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ataread.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ataread_.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ataread__nextbroken.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ataread_calc.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ataread_fat.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ataread_fatphy.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ataseek.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ataseek_relative.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atatell.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atawrite.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atawrite_close.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atawrite_fat.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atawrite_fatphy.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atawrite_write.c \
D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/version.c 

C_DEPS += \
./Atadisk.d \
./Atadiskfree.d \
./ata.d \
./ata_.d \
./ata_bytes.d \
./ata_bytes_seek.d \
./ata_bytes_write.d \
./ata_chdir.d \
./ata_fileinit.d \
./ata_flush.d \
./ata_labels.d \
./ata_labels_label.d \
./ata_labels_vol.d \
./ata_names.d \
./ata_readword.d \
./ata_sector.d \
./ata_timeout.d \
./ata_usb.d \
./atacreate.d \
./atacreate_findcluster.d \
./atacreatedir.d \
./atadir.d \
./atadir_.d \
./atadir__getdir.d \
./atadirentry.d \
./ataformat.d \
./atalong.d \
./atalong_create.d \
./atalong_create_rename.d \
./atalong_createentry.d \
./atalong_setname.d \
./ataread.d \
./ataread_.d \
./ataread__nextbroken.d \
./ataread_calc.d \
./ataread_fat.d \
./ataread_fatphy.d \
./ataseek.d \
./ataseek_relative.d \
./atatell.d \
./atawrite.d \
./atawrite_close.d \
./atawrite_fat.d \
./atawrite_fatphy.d \
./atawrite_write.d \
./version.d 

OBJS += \
./Atadisk.obj \
./Atadiskfree.obj \
./ata.obj \
./ata_.obj \
./ata_bytes.obj \
./ata_bytes_seek.obj \
./ata_bytes_write.obj \
./ata_chdir.obj \
./ata_fileinit.obj \
./ata_flush.obj \
./ata_labels.obj \
./ata_labels_label.obj \
./ata_labels_vol.obj \
./ata_names.obj \
./ata_readword.obj \
./ata_sector.obj \
./ata_timeout.obj \
./ata_usb.obj \
./atacreate.obj \
./atacreate_findcluster.obj \
./atacreatedir.obj \
./atadir.obj \
./atadir_.obj \
./atadir__getdir.obj \
./atadirentry.obj \
./ataformat.obj \
./atalong.obj \
./atalong_create.obj \
./atalong_create_rename.obj \
./atalong_createentry.obj \
./atalong_setname.obj \
./ataread.obj \
./ataread_.obj \
./ataread__nextbroken.obj \
./ataread_calc.obj \
./ataread_fat.obj \
./ataread_fatphy.obj \
./ataseek.obj \
./ataseek_relative.obj \
./atatell.obj \
./atawrite.obj \
./atawrite_close.obj \
./atawrite_fat.obj \
./atawrite_fatphy.obj \
./atawrite_write.obj \
./version.obj 

OBJS__QUOTED += \
"Atadisk.obj" \
"Atadiskfree.obj" \
"ata.obj" \
"ata_.obj" \
"ata_bytes.obj" \
"ata_bytes_seek.obj" \
"ata_bytes_write.obj" \
"ata_chdir.obj" \
"ata_fileinit.obj" \
"ata_flush.obj" \
"ata_labels.obj" \
"ata_labels_label.obj" \
"ata_labels_vol.obj" \
"ata_names.obj" \
"ata_readword.obj" \
"ata_sector.obj" \
"ata_timeout.obj" \
"ata_usb.obj" \
"atacreate.obj" \
"atacreate_findcluster.obj" \
"atacreatedir.obj" \
"atadir.obj" \
"atadir_.obj" \
"atadir__getdir.obj" \
"atadirentry.obj" \
"ataformat.obj" \
"atalong.obj" \
"atalong_create.obj" \
"atalong_create_rename.obj" \
"atalong_createentry.obj" \
"atalong_setname.obj" \
"ataread.obj" \
"ataread_.obj" \
"ataread__nextbroken.obj" \
"ataread_calc.obj" \
"ataread_fat.obj" \
"ataread_fatphy.obj" \
"ataseek.obj" \
"ataseek_relative.obj" \
"atatell.obj" \
"atawrite.obj" \
"atawrite_close.obj" \
"atawrite_fat.obj" \
"atawrite_fatphy.obj" \
"atawrite_write.obj" \
"version.obj" 

C_DEPS__QUOTED += \
"Atadisk.d" \
"Atadiskfree.d" \
"ata.d" \
"ata_.d" \
"ata_bytes.d" \
"ata_bytes_seek.d" \
"ata_bytes_write.d" \
"ata_chdir.d" \
"ata_fileinit.d" \
"ata_flush.d" \
"ata_labels.d" \
"ata_labels_label.d" \
"ata_labels_vol.d" \
"ata_names.d" \
"ata_readword.d" \
"ata_sector.d" \
"ata_timeout.d" \
"ata_usb.d" \
"atacreate.d" \
"atacreate_findcluster.d" \
"atacreatedir.d" \
"atadir.d" \
"atadir_.d" \
"atadir__getdir.d" \
"atadirentry.d" \
"ataformat.d" \
"atalong.d" \
"atalong_create.d" \
"atalong_create_rename.d" \
"atalong_createentry.d" \
"atalong_setname.d" \
"ataread.d" \
"ataread_.d" \
"ataread__nextbroken.d" \
"ataread_calc.d" \
"ataread_fat.d" \
"ataread_fatphy.d" \
"ataseek.d" \
"ataseek_relative.d" \
"atatell.d" \
"atawrite.d" \
"atawrite_close.d" \
"atawrite_fat.d" \
"atawrite_fatphy.d" \
"atawrite_write.d" \
"version.d" 

C_SRCS__QUOTED += \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/Atadisk.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/Atadiskfree.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_bytes.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_bytes_seek.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_bytes_write.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_chdir.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_fileinit.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_flush.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_labels.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_labels_label.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_labels_vol.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_names.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_readword.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_sector.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_timeout.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ata_usb.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atacreate.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atacreate_findcluster.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atacreatedir.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atadir.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atadir_.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atadir__getdir.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atadirentry.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ataformat.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atalong.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atalong_create.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atalong_create_rename.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atalong_createentry.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atalong_setname.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ataread.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ataread_.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ataread__nextbroken.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ataread_calc.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ataread_fat.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ataread_fatphy.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ataseek.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/ataseek_relative.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atatell.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atawrite.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atawrite_close.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atawrite_fat.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atawrite_fatphy.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/atawrite_write.c" \
"D:/dsp_filter/project_example_sine_750hz_1khz/ccs_v6.x_examples/drv/atafs/src/version.c" 


